### ISSUE TITLE
Deposit policies

### ISSUE THREAD

**Issue by honj** [honj/INFX-551-Spring2017#18]
who, what size, what format, etc.

**Comment by ftslyter** [comment]
Who: 
   We said, "somewhere on the continuum between a self-deposit repository and a submission repository." So are depositors making an account with us and/or filling out forms like QDR? 
What: 
   Deposit size limit = 100 MB
   Format = [Formating guidelines taken from Cornell.docx](https://github.com/honj/INFX-551-Spring2017/files/1012400/Formating.guidelines.taken.from.Cornell.docx)

**Comment by ghost** [comment]
This seems like a fairly significant part of our curation protocol that'll need it's own write-up as a section of our deliverable. 
Should we start with our deposit policies activity write-up as a base?

**Comment by honj** [comment]
Yes, I agree. We have a good start in the write-up that we can build on/refine.

**Comment by ftslyter** [comment]
I apologize if my question wasn't so easily seen:

So are depositors making an account with us and/or filling out forms like QDR?

**Comment by ghost** [comment]
This is a very good question... 
My thoughts:
Depositors would need to provide certain information along with datasets in order to submit them. This could take the shape of a web form. This might be a good idea to save labor in terms of repository management, even though it might be somewhat time-consuming for depositors? (As opposed to allowing required info to be submitted in whatever form is most convenient for depositors, which we would then need to transfer to our schema.)
And it seems like if there is the filling-out-of-online-forms, some kind of account would need to be created.

**Comment by honj** [comment]
I envision this falling somewhere on the continuum of self-deposit/submission. With one extreme being "users deposit with no human vetting" and the other being something heavy-touch like QDR, where there they do a lot of relationship building. We could have a form asking for the basic metadata, then follow up to get more information/clarification.

**Comment by ftslyter** [comment]
Thanks all.

**Comment by ftslyter** [comment]
Because our original deposit policy was so well put together, I only saw three places that needed updating to fall in line with our latest line of rationale. Rather than update our old Deposit Policy, I've attached my three tiny changes in this file; I've colored the three changes to make it easier to review. Because we are requiring a deposit form, I saw no need to add a mandatory account. Instead, I've included a user agreement in the deposit form itself.
[depositpolicy2.docx](https://github.com/honj/INFX-551-Spring2017/files/1030804/depositpolicy2.docx)
